// Regenerates src/TwStyling/Generated/TwPalette.g.cs from Tailwind's own theme.
//
// The engine reads colours from the compiled CSS, so this table is only used on the fallback path
// (a project with no tw.css). It must still agree with Tailwind, or that path would render a
// different palette — which is exactly the bug this file exists to prevent.
//
//   node tools/gen-palette.mjs <path-to-tailwindcss-cli>
//
// Tailwind v4 defines the palette in oklch. The conversion below is the same Oklab → sRGB matrix
// the engine uses in CssColorParser.cs, so the generated hexes match what the CSS pipeline
// produces at build time — the two paths cannot drift.

import { execFileSync } from 'node:child_process'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'

const cli = process.argv[2]
if (!cli) {
    console.error('usage: node tools/gen-palette.mjs <path-to-tailwindcss-cli>')
    process.exit(1)
}

const FAMILIES = [
    'slate', 'gray', 'zinc', 'neutral', 'stone',
    'red', 'orange', 'amber', 'yellow', 'lime',
    'green', 'emerald', 'teal', 'cyan', 'sky',
    'blue', 'indigo', 'violet', 'purple', 'fuchsia',
    'pink', 'rose',
]
const SHADES = ['50', '100', '200', '300', '400', '500', '600', '700', '800', '900', '950']

// Ask Tailwind for every palette colour: a @theme token only reaches the output if a utility uses it.
const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'tw-palette-'))
const entry = path.join(dir, 'palette.css')
const out = path.join(dir, 'palette.out.css')
fs.writeFileSync(entry, [
    '@import "tailwindcss";',
    `@source inline("bg-{${FAMILIES.join(',')}}-{${SHADES.join(',')}}");`,
].join('\n'))

execFileSync(cli, ['-i', entry, '-o', out], { stdio: 'pipe' })
const css = fs.readFileSync(out, 'utf8')

const linearToSrgb = c => (c <= 0.0031308 ? 12.92 * c : 1.055 * Math.pow(c, 1 / 2.4) - 0.055)

function oklchToHex(L, C, hDeg) {
    const h = (hDeg * Math.PI) / 180
    const a = C * Math.cos(h)
    const b = C * Math.sin(h)

    const l = (L + 0.3963377774 * a + 0.2158037573 * b) ** 3
    const m = (L - 0.1055613458 * a - 0.0638541728 * b) ** 3
    const s = (L - 0.0894841775 * a - 1.291485548 * b) ** 3

    const channels = [
        4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
        -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
        -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s,
    ]
    return channels
        .map(v => Math.max(0, Math.min(1, linearToSrgb(v))))
        .map(v => Math.round(v * 255).toString(16).padStart(2, '0').toUpperCase())
        .join('')
}

const colors = {}
for (const m of css.matchAll(/--color-([a-z]+)-(\d+):\s*oklch\(([\d.]+)(%?)\s+([\d.]+)\s+([\d.]+)\)/g)) {
    const [, family, shade, lightness, percent, chroma, hue] = m
    const L = percent ? parseFloat(lightness) / 100 : parseFloat(lightness)
    colors[`${family}-${shade}`] = oklchToHex(L, parseFloat(chroma), parseFloat(hue))
}

const entries = [
    '        ["transparent"] = 0x00000000,',
    '        ["black"] = 0xFF000000,',
    '        ["white"] = 0xFFFFFFFF,',
]
for (const family of FAMILIES) {
    for (const shade of SHADES) {
        const key = `${family}-${shade}`
        if (!colors[key]) throw new Error(`Tailwind emitted no --color-${key}`)
        entries.push(`        ["${key}"] = 0xFF${colors[key]},`)
    }
}

fs.writeFileSync(
    'src/TwStyling/Generated/TwPalette.g.cs',
    `// <auto-generated>
// Tailwind CSS v4 default color palette (MIT), generated from the Tailwind CLI's own
// oklch theme values by tools/gen-palette.mjs. Do not edit.
// </auto-generated>

using System.Collections.Generic;

namespace TwStyling;

public static partial class TwPalette
{
    /// <summary>Named palette entries mapped to 0xAARRGGBB.</summary>
    public static readonly IReadOnlyDictionary<string, uint> Colors = new Dictionary<string, uint>(System.StringComparer.Ordinal)
    {
${entries.join('\n')}
    };
}
`)

fs.rmSync(dir, { recursive: true, force: true })
console.log(`wrote ${entries.length - 3} palette entries (blue-500 = #${colors['blue-500']})`)
