param(
    [string]$InputFile,
    [string]$OutputFile
)

$lines = Get-Content $InputFile
$entries = [System.Collections.Generic.List[string]]::new()
$family = $null
$deprecated = @('lightBlue', 'warmGray', 'trueGray', 'coolGray', 'blueGray')

function Expand-Hex([string]$hex) {
    $h = $hex.TrimStart('#')
    if ($h.Length -eq 3) {
        $h = "$($h[0])$($h[0])$($h[1])$($h[1])$($h[2])$($h[2])"
    }
    return $h.ToUpperInvariant()
}

foreach ($line in $lines) {
    if ($line -match "^\s{2}(\w+): \{$") {
        $family = $Matches[1]
        if ($deprecated -contains $family) { $family = $null }
        continue
    }
    if ($line -match "^\s{2}\},?$") { $family = $null; continue }
    if ($null -ne $family -and $line -match "^\s{4}(\d+): '(#[0-9a-fA-F]{3,8})',?$") {
        $name = "$family-$($Matches[1])"
        $hex = Expand-Hex $Matches[2]
        $entries.Add("        [`"$name`"] = 0xFF$hex,")
        continue
    }
    if ($line -match "^\s{2}(black|white): '(#[0-9a-fA-F]{3,8})',?$") {
        $hex = Expand-Hex $Matches[2]
        $entries.Add("        [`"$($Matches[1])`"] = 0xFF$hex,")
    }
}

$header = @"
// <auto-generated>
// Tailwind CSS v3.4.17 default color palette (MIT), generated from
// tailwindcss/src/public/colors.js by tools/gen-palette.ps1. Do not edit.
// </auto-generated>

using System.Collections.Generic;

namespace Tw.Core;

public static partial class TwPalette
{
    /// <summary>Named palette entries mapped to 0xAARRGGBB.</summary>
    public static readonly IReadOnlyDictionary<string, uint> Colors = new Dictionary<string, uint>(System.StringComparer.Ordinal)
    {
        ["transparent"] = 0x00000000,
"@

$footer = @"
    };
}
"@

Set-Content -Path $OutputFile -Value ($header + "`n" + ($entries -join "`n") + "`n" + $footer) -Encoding utf8NoBOM
Write-Host "Wrote $($entries.Count + 1) colors to $OutputFile"
